# application_letter.typ
assets = "placeholder" # <- CHANGE ME

# Company contact
contact = ""
company = ""
street = ""
postal = ""
city = ""
mail = ""
phone = ""

vacancy = ""

content = """
..."""

