# meeting_protocol.typ
assets = "skarmux" # <- CHANGE ME

location = "Raum 4.07"

topic = "Who ate the parmesan cheese?"

[participants]
leader = [ # Preferably one entry!
    { name = "John Carmack", mail = "" }
]
reporter = [ # Preferably one entry!
    { name = "Bill Clinton", mail = "" }
]
present = [
    { name = "Arnold Schwarzenegger", mail = "" }
]
absent = [
    { name = "Nils Harbke", mail = "" }
]

[[agenda]]
issue = "Who uses the fridge?"
findings = [
    "Something is wrong.",
    "I can feel it."
]
decisions = [
    "Gonna do this and that.",
    "Have to do another thing."
]
tasks = [
    "Find Jason."
]

[[agenda]]
issue = "Who uses the fridge?"
findings = [
    "Something is wrong.",
    "I can feel it."
]
decisions = [
    "Gonna do this and that.",
    "Have to do another thing."
]
tasks = [
    "Find Jason."
]

[[agenda]]
issue = "Who uses the fridge?"
findings = [
    "Something is wrong.",
    "I can feel it."
]
decisions = [
    "Gonna do this and that.",
    "Have to do another thing."
]
tasks = [
    "Find Jason."
]

[[agenda]]
issue = "Who uses the fridge?"
findings = [
    "Something is wrong.",
    "I can feel it."
]
decisions = [
    "Gonna do this and that.",
    "Have to do another thing."
]
tasks = [
    "Find Jason."
]
